### ISSUE TITLE
ModuleNotFoundError: No module named 'pgl.contrib'

### ISSUE THREAD

**Issue by DMW123** [PaddlePaddle/PGL#229]
你好，遇到这个问题，请问是什么原因。谢谢
Traceback (most recent call last):
  File "/media/dell/TOSHIBA/Fuxian/PGL/ogb_examples/nodeproppred/unimp/main_arxiv.py", line 8, in <module>
    from pgl.contrib.ogb.nodeproppred.dataset_pgl import PglNodePropPredDataset
ModuleNotFoundError: No module named 'pgl.contrib'

**Comment by Yelrose** [comment]
应该是你的版本问题，ogb里面的任务，得安装paddlepaddle==1.8.5 PGL==1.2.1

pgl>=2.0和Paddle >= 2.0 动态图的UniMP，暂时还没提供。

**Comment by DMW123** [comment]
谢谢您，按照您的提示更改了版本，上一个问题解决了。但是又出现一个新的问题，麻烦您帮忙再看一下，感谢！
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "/media/dell/TOSHIBA/Fuxian/PGL/ogb_examples/nodeproppred/unimp/main_arxiv.py", line 4, in <module>
    import pgl
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/__init__.py", line 23, in <module>
    from pgl import nn
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/__init__.py", line 17, in <module>
    from pgl.nn import conv
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/conv.py", line 19, in <module>
    import paddle.nn as nn
ModuleNotFoundError: No module named 'paddle.nn'


> 应该是你的版本问题，ogb里面的任务，得安装paddlepaddle==1.8.5 PGL==1.2.1
> 
> pgl>=2.0和Paddle >= 2.0 动态图的UniMP，暂时还没提供。

**Comment by DMW123** [comment]
> 应该是你的版本问题，ogb里面的任务，得安装paddlepaddle==1.8.5 PGL==1.2.1
> 
> pgl>=2.0和Paddle >= 2.0 动态图的UniMP，暂时还没提供。

谢谢您，按照您的提示更改了版本，上一个问题解决了。但是又出现一个新的问题，麻烦您帮忙再看一下，感谢！
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Traceback (most recent call last):
  File "/media/dell/TOSHIBA/Fuxian/PGL/ogb_examples/nodeproppred/unimp/main_arxiv.py", line 4, in <module>
    import pgl
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/__init__.py", line 23, in <module>
    from pgl import nn
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/__init__.py", line 17, in <module>
    from pgl.nn import conv
  File "/media/dell/TOSHIBA/Fuxian/PGL/pgl/nn/conv.py", line 19, in <module>
    import paddle.nn as nn
ModuleNotFoundError: No module named 'paddle.nn'
