### ISSUE TITLE
Cublas error, CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by ciaranchen** [PaddlePaddle/PGL#259]
环境：
- NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: 10.2
- CUDNN 
    
    ```
    #define CUDNN_MAJOR 7
    #define CUDNN_MINOR 6
    #define CUDNN_PATCHLEVEL 4
    ```

- 单机单卡
- Operator信息：operator < mul > error
- Paddle及其他依赖版本

    根据`requirements.txt`在pypi下载了相应版本的`pgl-1.2.1-cp37-cp37m-manylinux1_x86_64.whl`, `paddlepaddle_gpu-1.8.3.post107-cp37-cp37m-manylinux1_x86_64.whl`和`torch-1.5.1-cp37-cp37m-manylinux1_x86_64.whl`文件，其余文件都是`pip install -r requirements.txt`安装。

在`PGL/ogb_examples/nodeproppred/ogbn-arxiv/unimp_appnp_vnode_smooth`文件夹中，参照`README.md`运行 `python main_arxiv_appnp_vnode_smooth.py --place 0 --use_label_e --log_file arxiv_unimp.txt` ，产生报错。完整输出如下：

```
===========args==============
Namespace(attn_dropout=0.1, dropout=0.3, epochs=1500, hidden_size=100, label_rate=0.65, log_file='arxiv_unimp.txt', lr=0.001, num_heads=3, num_layers=3, num_vnode=3, place=0, runs=10, use_label_e=True)
=============================
Loading necessary files...
This might take a while.
Processing graphs...
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 9238.56it/s](169343, 1)
(3, 128)
/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/layers/nn.py:4780: UserWarning: param_attr is only available with scale is True.
  warnings.warn("param_attr is only available with scale is True.")
/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/layers/nn.py:4788: UserWarning: bias_attr is only available with shift is True.
  warnings.warn("bias_attr is only available with shift is True.")
W0607 10:56:00.392354 20420 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0607 10:56:00.394553 20420 device_context.cc:260] device: 0, cuDNN Version: 7.6.
  0%|                                                                                          | 0/1500 [00:00<?, ?it/s]/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")

Traceback (most recent call last):
  File "main_arxiv_appnp_vnode_smooth.py", line 191, in <module>
    graph, label, split_idx, exe, run_i, wf)
  File "main_arxiv_appnp_vnode_smooth.py", line 108, in train_loop
    fetch_list=[model.avg_cost])
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1721, in fc
    "y_num_col_dims": 1})
  File "/home/lab401/Projects/PGL/ogb_examples/nodeproppred/ogbn-arxiv/unimp_appnp_vnode_smooth/module/model_unimp.py", line 268, in linear
    bias_attr=fc_bias_attr)
  File "/home/lab401/Projects/PGL/ogb_examples/nodeproppred/ogbn-arxiv/unimp_appnp_vnode_smooth/module/model_unimp.py", line 106, in graph_transformer
    q = linear(feature, hidden_size * num_heads, name=name + '_q_weight', init_type='gcn')
  File "/home/lab401/Projects/PGL/ogb_examples/nodeproppred/ogbn-arxiv/unimp_appnp_vnode_smooth/model.py", line 127, in build_model
    layer_norm=True, relu=True, gate=True)
  File "/home/lab401/Projects/PGL/ogb_examples/nodeproppred/ogbn-arxiv/unimp_appnp_vnode_smooth/model.py", line 82, in __init__
    self.build_model()
  File "main_arxiv_appnp_vnode_smooth.py", line 171, in <module>
    parser.dropout, parser.num_layers)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)  [operator < mul > error]
```

**Comment by ciaranchen** [comment]
推测与PaddlePaddle  的 [这个Issue](https://github.com/PaddlePaddle/Paddle/issues/24788)相似，但是因为安装过`paddlepaddle_gpu==1.8.5.post107`与`torch==1.8.1`，结果是同样的报错，所以不清楚如何解决。

**Comment by WeiyueSu** [comment]
贴一下显卡型号，试试paddle.fluid.install_check.run_check()看下log

**Comment by ciaranchen** [comment]
显卡的型号为 GeForce RTX 2080 Ti

运行 `paddle.fluid.install_check.run_check()` 是几乎与前面一样的报错。

```
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W0609 16:31:40.247915  2280 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0609 16:31:40.312302  2280 device_context.cc:260] device: 0, cuDNN Version: 7.6.
/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 122, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 962, in forward
    type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 41, in forward
    x = self._linear1(inputs)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/lab401/KG/an/envs/cjr/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)  [operator < matmul > error]
```

**Comment by ciaranchen** [comment]
咨询后发现也是安装cuda之中存在错误，在重新安装CUDA至10.2版本后解决了此问题。感谢@WeiyueSu 的解答。
